---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/albums/{id}":
    get:
      summary: Retrieves an album
      tags:
      - Albums
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: Album found
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  name:
                    type: string
                  release_date:
                    type: string
                    format: date
                required:
                - id
                - name
        '404':
          description: album not found
servers:
- url: http://localhost:3000
  variables:
    defaultHost:
      default: http://localhost:3000
